---
title: "Untitled"
author: "Mario Casas Gonzalez"
date: "August 7, 2018"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
library(shiny)
ui <- fluidPage(
  # App title ----
  titlePanel("Hello Shiny!"),
  # Sidebar layout with input and output definitions ----
  sidebarLayout(
    # Sidebar panel for inputs ----
    sidebarPanel(
      # Input: Slider for the number of bins ----
      sliderInput(inputId = "bins",
                  label = "Number of bins:",
                  min = 1,
                  max = 50,
                  value = 30)
    ),
    # Main panel for displaying outputs ----
    mainPanel(
      # Output: Histogram ----
      plotOutput(outputId = "distPlot")
    )
  )
)
#shinyApp(ui, server)
server <- function(input, output) {
  # Load packages
  library(tidyverse)
  # Histogram of the Old Faithful Geyser Data ----
  # with requested number of bins
  output$distPlot <- renderPlot({
    faithful %>% ggplot(aes(x = waiting)) +
      geom_histogram(bins = input$bins) +
      theme_bw()
  })
}


```

