---
title: "COMPSCIX 415.2 Homework 9/Final"
author: "Mario Casas Gonzalez"
date: "August 9, 2018"
output: 
  html_document:
    toc: TRUE
    theme: united 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)


```

```{r, warning = FALSE, message = FALSE}
library(tidyverse)
library(dplyr)
library(mdsr)
```



Hyperlink to my Github repository: https://github.com/casasgmario/compscix-415-2-assignments.git

## Exercise 1 - Sampling Distributions, Functions and For Loops (10 points)

###Step 1

```{r Exercise1-Step1, echo=TRUE}

samp_size <- 100
samp_rate <- 1/10000

samp_fun <- function(samp_size, samp_rate) {
my_samp <- rexp(n = samp_size, rate = samp_rate)
samp_avg <- mean (my_samp)
samp_std_dev <- sd(my_samp)
stats <- list(samp_avg = samp_avg, samp_std_dev = samp_std_dev)
return(stats)
}

samp_fun(samp_size, samp_rate)



```


###Step 2

```{r Exercise1-Step2, echo=TRUE}
n <- 1000 
samp_size <- 50
samp_rate <- 1/10000
sample_means <- c(0)
sample_sds <- c(0)


for (i in 1:n) {
  samp_size <- 50
  samp_rate <- 1/10000
  my_list <- samp_fun(samp_size, samp_rate)
  sample_means[[i]] <- my_list$samp_avg
  sample_sds[[i]] <- my_list$samp_std_dev
}

```


###Step 3

```{r Exercise1-Step3, echo=TRUE}
sample_means_df <- as_data_frame(sample_means)
ggplot(sample_means_df, aes(x=value)) + geom_histogram()
my_sd <- sd(sample_means)
my_sd
theor_std_error <- my_sd/sqrt(samp_size)


```

###Step 4

```{r Exercise1-Step4, echo=TRUE}

n <- 1000 
samp_size <- 500
samp_rate <- 1/10000
sample_means <- c(0)
sample_sds <- c(0)


for (i in 1:n) {
  samp_size <- 50
  samp_rate <- 1/10000
  my_list <- samp_fun(samp_size, samp_rate)
  sample_means[[i]] <- my_list$samp_avg
  sample_sds[[i]] <- my_list$samp_std_dev
}

sample_means_df <- as_data_frame(sample_means)
ggplot(sample_means_df, aes(x=value)) + geom_histogram()
my_sd <- sd(sample_means)
my_sd
theor_std_error <- my_sd/sqrt(samp_size)

samp_size <- 5000

for (i in 1:n) {
  samp_size <- 50
  samp_rate <- 1/10000
  my_list <- samp_fun(samp_size, samp_rate)
  sample_means[[i]] <- my_list$samp_avg
  sample_sds[[i]] <- my_list$samp_std_dev
}

sample_means_df <- as_data_frame(sample_means)
ggplot(sample_means_df, aes(x=value)) + geom_histogram()
my_sd <- sd(sample_means)
my_sd
theor_std_error <- my_sd/sqrt(samp_size)

```



